remote_theme: samarsault/plainwhite-jekyll
theme: plainwhite

plainwhite:
  name: Paul Stocker
  tagline: PhD Student
  date_format: "%b %-d, %Y"
  sitemap: true
  portfolio_image:  "assets/portfolio.png" 
  dark_mode: true

  social_links:
    github:  PaulSt
    linkedIn: in/paul-stocker-63961a121/ # format: locale/username

  navigation:
    - title: Home
      url: "/index"
    - title: Travel
      url: "/travel"

#permalink: /:year/:categories/:title:output_ext
permalink: post/:title

plugins:
  - jekyll-seo-tag

title: "Paul Stocker"
description: "Paul Stocker, mathematics, math, Mathematik, Mathe, PhD Student, PhD, Vienna, univie, University of Vienna, Wien"
webmaster_verifications:
  google: "ByYdzwgMKaBTrHM7VNNajWnJg8yfcSU41D7OF6E_p1Q"
