theme: eleven-theme

eleven:
  name: Umberto Zerbinati
  date_format: "%b %d, %Y"
  logo:  "assets/logo.jpeg"

permalink: post/:title

title: "Umberto Zerbinati"
description: "Umberto Zerbinati, DPhil student Oxford University"
webmaster_verifications:
  #google: "ByYdzwgMKaBTrHM7VNNajWnJg8yfcSU41D7OF6E_p1Q"

excerpt_separator: <!--more-->
page_excerpts: true
