#remote_theme: PaulSt/eleven
theme: eleven-theme

eleven:
  name: Paul Stocker
  date_format: "%b %d, %Y"
  #logo:  "assets/logo.png" 

permalink: post/:title

title: "Paul Stocker"
description: "Paul Stocker, mathematician, Post-Doc Uni Göttingen, Mail: p.stocker@math.uni-goettingen.de"
webmaster_verifications:
  google: "ByYdzwgMKaBTrHM7VNNajWnJg8yfcSU41D7OF6E_p1Q"

excerpt_separator: <!--more-->
page_excerpts: true
