remote_theme: thelehhman/plainwhite-jekyll
theme: plainwhite

plainwhite:
  name: Paul Stocker
  tagline: PhD Student
  date_format: "%b %-d, %Y"
  sitemap: true

  social_links:
    github:  PaulSt
    linkedIn: in/paul-stocker-63961a121/ # format: locale/username

permalink: /:year/:categories/:title:output_ext

plugins:
  - jekyll-seo-tag

title: "Paul Stocker"
description: "Paul Stocker, Mathematics, PhD Student"
webmaster_verifications:
  google: "ByYdzwgMKaBTrHM7VNNajWnJg8yfcSU41D7OF6E_p1Q"
