theme: eleven-theme

eleven:
  name: Algebraic Methods in Kinetic Theory and Calculus of Variations
  date_format: "%b %d, %Y"
  logo:  ""

permalink: /

title: "Algebraic Methods in Kinetic Theory and Calculus of Variations"
description: ""
webmaster_verifications:
  #google: "ByYdzwgMKaBTrHM7VNNajWnJg8yfcSU41D7OF6E_p1Q"

excerpt_separator: <!--more-->
page_excerpts: true
